### ISSUE TITLE
Error on  cargo run --release

### ISSUE THREAD

**Issue by ram0973** [robmikh/minesweeper-rs#11]
Compiling winmd_macros v0.1.0 (https://github.com/microsoft/winrt-rs#837e0cb1)
error[E0432]: unresolved import `proc_macro`
 --> C:\Users\Ra\.cargo\git\checkouts\winrt-rs-5b24704ba4b09dbb\837e0cb\crates\winmd\macros\src\lib.rs:1:5
  |
1 | use proc_macro::TokenStream;
  |     ^^^^^^^^^^ help: a similar path exists: `syn::proc_macro`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `winmd_macros`.
warning: build failed, waiting for other jobs to finish...
error: build failed
PS C:\Users\Ra\minesweeper-rs>

**Comment by robmikh** [comment]
Huh... that's odd. I'm unable reproduce this. What version of the rust compiler are you using?

```
rustc --version
```

I'm running `rustc 1.43.0 (4fb7144ed 2020-04-20)`.

**Comment by ram0973** [comment]
rustc 1.41.1 (f3e1a954d 2020-02-24)

**Comment by robmikh** [comment]
Ok, after installing that version of the toolchain I'm able to reproduce this. It looks like this was fixed in a newer version of the rust compiler. I would try `rustup update` and try again. If you need to keep that specific version, you can do the following:

```
rustup toolchain install 1.43.0
cargo +1.43.0 run --release
```

**Comment by ram0973** [comment]
rustc 1.43.0 (4fb7144ed 2020-04-20) work like a charm. Thanks a lot!
