### ISSUE TITLE
Cargo.lock prevents compiling by third parties

### ISSUE THREAD

**Issue by zingus** [robmikh/minesweeper-rs#12]
Cargo.lock should be taken out of version control, perhaps?

**Comment by zingus** [comment]
Actually nevermind. Compilation halted anyway on winmd_macro, then I updated the whole of rust and succeeded in compiling it.

After the rustup update having the versioned Cargo.lock laying around seems not to cause anymore any issues whatsoever.

**Comment by kennykerr** [comment]
It's still a good idea not to add `Cargo.lock` to the repo via `.gitignore`.

**Comment by Dr-Emann** [comment]
For an executable like this, it is recommended to keep the lock file in version control

**Comment by robmikh** [comment]
I second @Dr-Emann, the Cargo FAQ states that applications which are at the end of the dependency chain should keep their Cargo.lock to provide successful deterministic builds. Libraries should not, to avoid things like version conflicts:

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

@zingus, it's likely you hit this issue: https://github.com/robmikh/minesweeper-rs/issues/11. But it sounds like you got it sorted out! 🙂

**Comment by kennykerr** [comment]
Good to know - thanks!
