### ISSUE TITLE
app not release

### ISSUE THREAD

**Issue by mojaeb** [robmikh/minesweeper-rs#13]
run this
```
cargo run --release
```
 in terminal but i have error
![image](https://user-images.githubusercontent.com/39630146/80863327-b3ec2b80-8c90-11ea-8ebb-e237552b3417.png)

**Comment by rylev** [comment]
Which version of Rust are you using? This seems to be due to using an old toolchain. If you installed Rust using rustup, run `rustup update`

**Comment by robmikh** [comment]
Yeah, this looks like the same error message like in https://github.com/robmikh/minesweeper-rs/issues/11.

**Comment by ram0973** [comment]
On Windows fresh new installed version is old.
